[package]
name = "k8p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.83.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.18.0", features = ["v1_26"] }
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread", "signal"] }
csv = "1.1"
