name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Cluster
      uses: helm/kind-action@v1.8.0
    - name: 'Install Charts'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'my-navitain'
        namespace: 'default'
        chart: 'navicore/navitain'
        repo: 'https://www.navicore.tech/charts'
        repo-alias: navicore
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
