name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Cluster
      uses: helm/kind-action@v1.8.0
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0
    - name: Install Navicore Charts
      run |
        helm install my-navitain https://www.navicore.tech/charts/navitain-0.1.10.tgz
        end=$((SECONDS+60))  # 60 seconds from now
        while [ $SECONDS -lt $end ]; do
            # Check if the pod is in Running status
            # app.kubernetes.io/name=navitain
            STATUS=$(kubectl get po -l app.kubernetes.io/name=navitain -o jsonpath="{.items[*].status.phase}")
            if [ "$STATUS" == "Running" ]; then
                echo "Pod is running"
                break
            fi
            echo "Waiting for pod to be in running state..."
            sleep 2  # polling interval
        done

        if [ "$STATUS" != "Running" ]; then
            echo "Timed out waiting for pod to become Running."
            exit 1
        fi
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
